### ISSUE TITLE
Doesn't open in Windows 11

### ISSUE THREAD

**Issue by erangalds** [microsoft/Analysis-Services#261]
I installed ALM Toolkit the latest version downloaded from the Website. It doesn't open. My Windows version 23H2 (OS Build 22631.3672). I throws couple of errors. 

First Error. 
Application: AlmToolkit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at AlmToolkit.ComparisonForm.InitializeChromium()
   at AlmToolkit.ComparisonForm..ctor()
   at AlmToolkit.Program.Main(System.String[])

Second Error. 
Faulting application name: AlmToolkit.exe, version: 5.0.44.0, time stamp: 0x649a2fda
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3672, time stamp: 0xf527a1c6
Exception code: 0xe0434352
Fault offset: 0x00149a72
Faulting process id: 0x0xCC0
Faulting application start time: 0x0x1DAB278D4891888
Faulting application path: C:\Program Files\Power BI ALM Toolkit\Power BI ALM Toolkit\AlmToolkit.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5310f984-bf72-4506-8ce1-89c371315dd5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by erangalds** [comment]
Thanks Christian. I will surely do. I tried with another Windows 11 setup. It didn't work either. Therefore I am guessing that all Windows 11 users must be having this problem.

**Comment by christianwade** [comment]
Are you using a corporate/pre-defined Windows build? Lots of other users are using Windows 11 including here at Microsoft. There may still be something environmental. As I say, I hope the new release will resolve.
