### ISSUE TITLE
ASTrace for SSAS 2017

### ISSUE THREAD

**Issue by SQLPRODDBA** [microsoft/Analysis-Services#45]
What changes needs to be done during install of ASTrace for SSAS 2017?

**Comment by ubenmackin** [comment]
I'm also looking to try and get it running on 2019. Currently I get the following error:

6/17/2020 5:27:26 PM:  Service Started in 'D:\Software\ASTrace2016'
6/17/2020 5:27:26 PM:  Cannot start Analysis Server trace: 
6/17/2020 5:27:26 PM:  Analysis Server name: 'localhost\tabular'
6/17/2020 5:27:26 PM:  Trace definition : 'D:\Software\ASTrace2016\Standard.tdf'
6/17/2020 5:27:26 PM:  Error: Failed to initialize object as reader.
6/17/2020 5:27:26 PM:  Stack Trace:    at Microsoft.SqlServer.Management.Trace.TraceServer.InitializeAsReader(ConnectionInfoBase serverConnInfo, String profileFileName)
   at ASTrace.Trace.ConnectOlap(TraceServer& traceServer, String SSASserver) in C:\Scratch\Analysis-Services-master\AsTrace\ASTrace CS - 2016\ASTrace\Service1.cs:line 124
INNER EXCEPTION: Failed to create an instance of type Microsoft.SqlServer.Management.Trace.CTraceObjectsRowsetController.
   at Microsoft.SqlServer.Management.Trace.TraceUtils.CreateInstance(String assemblyRelativePath, String objectClass)
   at Microsoft.SqlServer.Management.Trace.TraceServer.InitializeAsReader(ConnectionInfoBase serverConnInfo, String profileFileName)

6/17/2020 5:27:26 PM:  Exception caught tracing server: localhost\tabular, retry 1 of 3. Pausing for 5 minute(s) then restarting automatically
