### ISSUE TITLE
I can't open AsPartitionProcessing.AdventureWorks.smproj

### ISSUE THREAD

**Issue by feco93** [microsoft/Analysis-Services#9]
I tried SQL SERVER 2017, SSDT for VS 2015 and SQL SERVER 2017, SSDT for VS 2017 combinations. 

The error message:
An error occurred while opening the model on the workspace database. Reason: Input string was not in a correct format.
============================
Call Stack:
============================
   at Microsoft.AnalysisServices.VSHost.VSHostManager.PrepareSandbox(Boolean newProject, Boolean& isRefreshNeeded, Boolean& isImpersonationChanged, Boolean& saveRequired, List`1& truncatedTables, Boolean isRealTimeMode, Int32 clientCompatibilityLevel)
   at Microsoft.AnalysisServices.VSHost.Integration.EditorFactory.CreateEditorInstance(UInt32 grfCreateDoc, String pszMkDocument, String pszPhysicalView, IVsHierarchy pvHier, UInt32 itemid, IntPtr punkDocDataExisting, IntPtr& ppunkDocView, IntPtr& ppunkDocData, String& pbstrEditorCaption, Guid& pguidCmdUI, Int32& pgrfCDW)

**Comment by baatch** [comment]
I also have the same problem when trying to open the model.bim.

Please help.

**Comment by Geraldziu** [comment]
Did you try to open model in integrated workspace?

**Comment by LaguideHalid** [comment]
I also have the same problem when trying to open the model.bim.

Please help.

**Comment by christianwade** [comment]
Please check using integrated workspace mode and using the latest AS SSDT extension

**Comment by LaguideHalid** [comment]
Hello @christianwade 
Thank you for your help.
I will try with a latest AS SSDT extension.
So far I have been able to open the BIM file with Tabular Editor and it works.

**Comment by LaguideHalid** [comment]
hello
I also have the same problem when trying to open the model.bim.
Did you find the issue in the .bim file ? 
Please help.

**Comment by christianwade** [comment]
Hi, did you try using the integrated workspace instead of a SSAS instance?
